### PR TITLE
Feature: openapi doc gen

### PR DESCRIPTION
**Pull request by kazelone**
Create a saphir_cli command line utility for saphir, and add to it the doc-gen function for generating openapi v3 documentation automatically from a saphir project using #[controller] macros.

### CODE REVIEW

**Comment by kazelone** [comment]
@richerarc "crate_syn_browser" could eventually be improved and be it's own crate; It's general enough to be useful to any kind of static rust project analysis, I think.

**Comment by richerarc** [comment]
First All your files are missing a newline at the end, just make sure to add that.
Then, the "cli" part seems to be missing, can it be run as a cargo subcommand & you should probably use `clap` crate to at least be able to show a basic command help and some options

**Comment by kazelone** [comment]
> First All your files are missing a newline at the end, just make sure to add that.
> Then, the "cli" part seems to be missing, can it be run as a cargo subcommand & you should probably use `clap` crate to at least be able to show a basic command help and some options

It's alrealy a cli with help and options.
running cargo install inside the root project dir (where the workspace Cargo.toml is located), or, once it is merged and published on crates.io, just `cargo install saphir`, install the saphir_cli.
running saphir_cli initially show help.

doc gen is a command ran with `saphir_cli doc-gen`. `saphir_cli doc-gen --help` or `saphir_cli doc-gen -h` show it's help; it got a couple of flags available.

**Comment by richerarc** [comment]
true I didn't see the structopt effect, tho the cli should be named saphir for simpler & shorter user (e.g. `saphir doc-gen`), and since this tools only generate openapi files, I wouldn't it be more appropriate to call the sub command openapi, with a specific sub command like gen. This would give the nice and common pattern : `saphir openapi gen`

**Comment by kazelone** [comment]
> true I didn't see the structopt effect, tho the cli should be named saphir for simpler & shorter user (e.g. `saphir doc-gen`), and since this tools only generate openapi files, I wouldn't it be more appropriate to call the sub command openapi, with a specific sub command like gen. This would give the nice and common pattern : `saphir openapi gen`

Agreed with just "saphir, however I'm not sure if it's possible to name both the lib and the bin targets "saphir". I'll look into it.

For the `saphir openapi gen`, I agree, but this makes me think that if we plan on doing generation for other things, it could be instead `saphir gen openapi`, or `saphir gen controller`... but then, `saphir add controller` would make more sense, and we could have other openapi commands like `saphir openapi gen-controller-from-openapi` (dunno how to call it).

I'm 100% for renaming the doc-gen command to something else but just unsure what would be best

**Comment by kazelone** [comment]
> true I didn't see the structopt effect, tho the cli should be named saphir for simpler & shorter user (e.g. `saphir doc-gen`), and since this tools only generate openapi files, I wouldn't it be more appropriate to call the sub command openapi, with a specific sub command like gen. This would give the nice and common pattern : `saphir openapi gen`

Agreed with just "saphir, however I'm not sure if it's possible to name both the lib and the bin targets "saphir". I'll look into it.

For the `saphir openapi gen`, I agree, but this makes me think that if we plan on doing generation for other things, it could be instead `saphir gen openapi`, or `saphir gen controller`... but then, `saphir add controller` would make more sense, and we could have other openapi commands like `saphir openapi gen-controller-from-openapi`...

**Comment by richerarc** [comment]
The build seems completely broken, your last commit had unexpected side effects

**Comment by kazelone** [comment]
> The build seems completely broken, your last commit had unexpected side effects

You meant the hyper 0.13.6 thing that I fixed or something else? @richerarc

**Comment by richerarc** [comment]
I'm not a big fan of the unsafe, but I understand why it's there, and honestly I don't see an easy work around to remove it without impacting the whole codebase, so LGTM

**Pull request merged**
