### PR TITLE
File middleware now handles HEAD requests correctly

### LINKED ISSUE #141: [BUG] FileMiddleware issue: HEAD request on a file doesn't cache the file properly
**Description**
If you use the FileMiddleware with a cache, there is an issue if you receive a HEAD request on a file before any GET request. The problem is that we save in cache an empty file since we don't read it so we save an empty file in cache. All GET request receive after don't return the file as expected.

(Of course, the file has to be cached. Depending of the cache configuration, it could work or not. But for sure, you can get cases that don't work)

**Expected behavior**
GET request on a file should return the file, even if we have receive a HEAD request before.

**Additional info (please complete the following information):**
 - Saphir Version: 2.8

### PR DESCRIPTION
**Pull request by LucFauvel**
Skips file reading for HEAD requests and return an empty body in file middleware

Closes #141

### CODE REVIEW

**Comment by fdubois1** [comment]
I agree with the fix. But I think the code support RANGE header and we could receive a request to a range only. In a such case, what will be saved in cache ?  The full file or only the range requested ? I just want to be sure that we support all cases. Thanks

**Comment by LucFauvel** [comment]
@fdubois1 When a get request is sent with Range headers the whole file is still read and put in cache, I just made it so that in the case of a Head request with a range it returns the correct ranges in the headers without reading the file (because you don't actually need to read the file to get the size).

**Comment by fdubois1** [comment]
@LucFauvel Ok, if we read the whole file even if we receive a request with a Range header, we are all good... but I had the feeling that we read only what is needed.  When we set a range, we seek to that position before reading, no ?  https://github.com/richerarc/saphir/blob/master/saphir/src/file/mod.rs#L329

But I didn't read the full code, I might be wrong.

**Comment by LucFauvel** [comment]
@fdubois1 that is partially correct, by that point the whole file has already been cached and its only the read stream of the file already loaded in cache/memory that seeks to the correct position, not the read on the actual file during the cache process.

**Pull request merged**
